# -*- coding: utf-8 -*-
"""q1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1syGTkCg-msDnvT6iw7z5bz59pacFQk8S
"""

num = [5, 8, 1, 2, 5]
print(num.count(5))