# -*- coding: utf-8 -*-
"""q2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1syGTkCg-msDnvT6iw7z5bz59pacFQk8S
"""

num = [5, 6, 7, 8, 9, 10]
sum = 0;

for i in num:
  sum+=i
print(sum/len(num))