# -*- coding: utf-8 -*-
"""q3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1syGTkCg-msDnvT6iw7z5bz59pacFQk8S
"""

num = [5, 6, 7, 8, 9, 10]

print(f"maior: {max(num)} / menor: {min(num)}")