# -*- coding: utf-8 -*-
"""q4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1syGTkCg-msDnvT6iw7z5bz59pacFQk8S
"""

num = input().split()
lista = []
listaPar = []

for i in num:
    lista.append(int(i))
for i in lista:
  if i%2 == 0:
    listaPar.append(i)
print(listaPar)