# -*- coding: utf-8 -*-
"""q5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1syGTkCg-msDnvT6iw7z5bz59pacFQk8S
"""

lista1 = input().split()
lista2 = input().split()
listaFinal = []

for i in lista1:
  listaFinal.append(int(i))
for i in lista2:
  listaFinal.append(int(i))

print(sorted(listaFinal))